<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No WhatsApp_phone</name>
   <tag></tag>
   <elementGuidId>c85dafe0-0dc5-468f-abc9-b0a87079920c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c49899a-76f0-441c-900e-82a25f9f2d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3abd7b22-06c8-44a1-9a25-a8ed5255d550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>96d92de6-4bb9-47af-90c8-fbdfbf26105d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No WhatsApp</value>
      <webElementGuid>8d86b56c-6ed9-4ea1-a888-dc27060475b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-xs md:text-sm border-gray-300 rounded-md</value>
      <webElementGuid>5ee91267-d610-4000-a3e6-8b20b50c468a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-gray-100&quot;]/main[@class=&quot;bg-main&quot;]/div[@class=&quot;max-w-2xl mx-auto py-8 px-4 sm:py-14 sm:px-6 lg:max-w-7xl lg:px-8&quot;]/div[@class=&quot;lg:grid lg:grid-cols-12 lg:gap-8&quot;]/div[@class=&quot;mt-16 sm:mt-24 lg:mt-0 lg:col-span-6&quot;]/div[@class=&quot;bg-white sm:max-w-md sm:w-full sm:mx-auto sm:rounded-lg sm:overflow-hidden&quot;]/div[@class=&quot;px-4 py-8 sm:px-10&quot;]/div[@class=&quot;mt-6&quot;]/span[1]/form[1]/div[@class=&quot;py-1&quot;]/input[@class=&quot;block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-xs md:text-sm border-gray-300 rounded-md&quot;]</value>
      <webElementGuid>d92a07fd-0a25-4fa3-b6cb-483076b6da46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>2856d6bf-e6be-4bcf-abff-d4b73f5def26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div[3]/span/form/div[3]/input</value>
      <webElementGuid>4a68c013-e700-416c-bcaa-5a50e069ca1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d54e3141-f634-4225-b809-7e5c0b6f483d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phone' and @placeholder = 'No WhatsApp']</value>
      <webElementGuid>b5234f45-71ff-43ac-95f7-b577e06c71c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
