<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_name</name>
   <tag></tag>
   <elementGuidId>6378b242-cee3-4ff5-84f2-72ff6752e423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1937410c-d72a-45db-b8a4-4b86ed754a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c7958ac-6f7e-4c89-856d-57908bc94037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>a475d683-a9c8-4521-adc6-d15863ad1697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>e22011c1-ed47-4e77-af59-f5d87f3f23fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-xs md:text-sm border-gray-300 rounded-md</value>
      <webElementGuid>4f77ce68-9957-4255-a4f7-49ce41c2be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-gray-100&quot;]/main[@class=&quot;bg-main&quot;]/div[@class=&quot;max-w-2xl mx-auto py-8 px-4 sm:py-14 sm:px-6 lg:max-w-7xl lg:px-8&quot;]/div[@class=&quot;lg:grid lg:grid-cols-12 lg:gap-8&quot;]/div[@class=&quot;mt-16 sm:mt-24 lg:mt-0 lg:col-span-6&quot;]/div[@class=&quot;bg-white sm:max-w-md sm:w-full sm:mx-auto sm:rounded-lg sm:overflow-hidden&quot;]/div[@class=&quot;px-4 py-8 sm:px-10&quot;]/div[@class=&quot;mt-6&quot;]/span[1]/form[1]/div[@class=&quot;py-1&quot;]/input[@class=&quot;block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 text-xs md:text-sm border-gray-300 rounded-md&quot;]</value>
      <webElementGuid>83f3edd7-5a13-477c-a08a-91a063a4dc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>f7119d4c-4497-4f94-bd11-d0b1913dbe08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div[3]/span/form/div/input</value>
      <webElementGuid>263bbc36-4b9c-4304-87f3-ca9027a0aee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>707dd3d8-108f-47e1-859f-693906f308ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @placeholder = 'Nama']</value>
      <webElementGuid>8b109fa7-fa46-4638-9efe-63692a06eaae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
